name: CI Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    name: ğŸ› ï¸ Build Project
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4.1.4
      
      - name: ğŸ“¦ Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.11.x
      
      - name: ğŸ“¦ Install dependencies
        run: npm install
      
      - name: ğŸ› ï¸ Build PWA
        run: npm run build
      
      - name: ğŸ“¦ Upload Build Artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: build-artifacts
          path: "./dist/pwa/"

  deploy:
    name: ğŸ‰ Deploy to FTP Server
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4.1.4
      
      - name: ğŸ“‚ Download Build Artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: build-artifacts
          path: "./dist/pwa/"
      
      - name: ğŸ“‚ Sync files to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/pwa/
          server-dir: /anzen/
          dangerous-clean-slate: true
          exclude: |
            .git*
            node_modules/
            README.md
            .github/
